
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/might?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8&serverTimezone=GMT
    username: root
    password: abc123456


  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    database: 0
    # redis服务器地址（默认为localhost）
    host: localhost
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位为毫秒）
    timeout: 5000
    # redis连接池配置
    jedis:
      pool:
      # 最大可用连接数（默认为8，负数表示无限）
        max-active: 13
      # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 13
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1

  cache:
    type: redis
    cache-names: hello,world
    #redis:
      #time-to-live: 60

  # mybatis配置
mybatis:
      # 配置映射类所在包名
  type-aliases-package: com.example.demo
  # 配置mapper xml文件所在路径，这里是一个数组
  mapper-locations: mappers/ProductMapper.xml

logging:
  level:
    com.example.demo: DEBUG

---
spring:
  profiles: test
  # 数据库配置http://localhost:8082
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql


